"""empty message

Revision ID: 05ad05247560
Revises: 12bc06f6006e
Create Date: 2020-09-15 11:30:27.251459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05ad05247560'
down_revision = '12bc06f6006e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data12', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('data13', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data', schema=None) as batch_op:
        batch_op.drop_column('data13')
        batch_op.drop_column('data12')

    # ### end Alembic commands ###
