"""empty message

Revision ID: 0a2e029c55b5
Revises: 1d77e324f10b
Create Date: 2020-09-18 14:28:02.145383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a2e029c55b5'
down_revision = '1d77e324f10b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('site_in')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_in',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('area', sa.VARCHAR(length=10), nullable=False),
    sa.Column('point', sa.VARCHAR(length=10), nullable=False),
    sa.Column('pointea', sa.INTEGER(), nullable=True),
    sa.Column('remark', sa.VARCHAR(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
