"""empty message

Revision ID: 24be715a97d9
Revises: 05ad05247560
Create Date: 2020-09-16 10:58:29.718455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24be715a97d9'
down_revision = '05ad05247560'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('point', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cst16', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('cst17', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('cst18', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('point', schema=None) as batch_op:
        batch_op.drop_column('cst18')
        batch_op.drop_column('cst17')
        batch_op.drop_column('cst16')

    # ### end Alembic commands ###
