"""empty message

Revision ID: 49caba41254e
Revises: f1dcb0244bd2
Create Date: 2020-09-14 10:57:21.729203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49caba41254e'
down_revision = 'f1dcb0244bd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data09', sa.String(length=400), nullable=True))
        batch_op.add_column(sa.Column('data10', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data', schema=None) as batch_op:
        batch_op.drop_column('data10')
        batch_op.drop_column('data09')

    # ### end Alembic commands ###
