"""empty message

Revision ID: cf098aa85365
Revises: 
Create Date: 2020-09-01 13:27:11.463470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf098aa85365'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('point',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('area', sa.String(length=10), nullable=True),
    sa.Column('number', sa.String(length=10), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('installdate', sa.Date(), nullable=True),
    sa.Column('startdate', sa.Date(), nullable=True),
    sa.Column('enddate', sa.Date(), nullable=True),
    sa.Column('locate', sa.String(length=20), nullable=True),
    sa.Column('active', sa.Integer(), nullable=True),
    sa.Column('cst01', sa.Float(), nullable=True),
    sa.Column('cst02', sa.Float(), nullable=True),
    sa.Column('cst03', sa.Float(), nullable=True),
    sa.Column('cst04', sa.Float(), nullable=True),
    sa.Column('cst05', sa.Float(), nullable=True),
    sa.Column('cst06', sa.Float(), nullable=True),
    sa.Column('cst07', sa.Float(), nullable=True),
    sa.Column('cst08', sa.Float(), nullable=True),
    sa.Column('cst09', sa.Float(), nullable=True),
    sa.Column('cst10', sa.Float(), nullable=True),
    sa.Column('cst11', sa.Float(), nullable=True),
    sa.Column('cst12', sa.Float(), nullable=True),
    sa.Column('cst13', sa.Float(), nullable=True),
    sa.Column('cst14', sa.Float(), nullable=True),
    sa.Column('cst15', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('site',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('fullname', sa.String(length=30), nullable=False),
    sa.Column('nickname', sa.String(length=10), nullable=False),
    sa.Column('service', sa.String(length=30), nullable=False),
    sa.Column('order', sa.String(length=10), nullable=True),
    sa.Column('supervisor', sa.String(length=10), nullable=True),
    sa.Column('constructor', sa.String(length=10), nullable=True),
    sa.Column('cost', sa.BigInteger(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fullname'),
    sa.UniqueConstraint('nickname')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('truename', sa.String(length=20), nullable=False),
    sa.Column('company', sa.String(length=20), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=20), nullable=False),
    sa.Column('power', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('point_id', sa.Integer(), nullable=True),
    sa.Column('measuringdate', sa.DateTime(), nullable=True),
    sa.Column('data01', sa.Float(), nullable=True),
    sa.Column('data02', sa.Float(), nullable=True),
    sa.Column('data03', sa.Float(), nullable=True),
    sa.Column('data04', sa.Float(), nullable=True),
    sa.Column('data05', sa.Float(), nullable=True),
    sa.Column('data06', sa.Float(), nullable=True),
    sa.Column('data07', sa.Float(), nullable=True),
    sa.Column('data08', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['point_id'], ['point.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data')
    op.drop_table('user')
    op.drop_table('site')
    op.drop_table('point')
    # ### end Alembic commands ###
