"""empty message

Revision ID: f1dcb0244bd2
Revises: 813c2f0cbc27
Create Date: 2020-09-02 08:43:48.919364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1dcb0244bd2'
down_revision = '813c2f0cbc27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site', schema=None) as batch_op:
        batch_op.add_column(sa.Column('endcost', sa.BigInteger(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site', schema=None) as batch_op:
        batch_op.drop_column('endcost')

    # ### end Alembic commands ###
